---
- name: Create restart flag
  become: true
  ansible.builtin.file:
    path: /tmp/x509.restart
    state: touch
  changed_when: false

- name: X509_exporter | create config file
  become: true
  ansible.builtin.template:
    src: "x509_exporter.default.conf.j2"
    dest: "{{ x509_exporter_config_file }}"
    owner: root
    group: root
    mode: "0640"
  notify: Restart
  register: config

- name: Delete restart flag
  become: true
  ansible.builtin.file:
    path: /tmp/x509.restart
    state: absent
  when: not config.changed
  changed_when: false
