---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance01
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-centos8-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    v: 2
lint: |
  set -e
  yamllint .
  ansible-lint -v
